-- ScanFlow initial schema.
--
-- Hand-written rather than generated by `drizzle-kit generate`, because the two
-- constraints this schema exists to enforce -- no resource and no patient ever
-- double-booked -- are Postgres EXCLUDE constraints, which Drizzle's schema
-- builder cannot express. See docs/adr/0001-postgres-exclusion-constraints.md.

CREATE EXTENSION IF NOT EXISTS btree_gist;
--> statement-breakpoint

CREATE TYPE resource_type AS ENUM ('DOCTOR', 'NMT_ROOM', 'SCAN_ROOM');
--> statement-breakpoint

CREATE TYPE segment_kind AS ENUM ('SERVICE', 'DELAY');
--> statement-breakpoint

CREATE TYPE segment_status AS ENUM ('ACTIVE', 'CANCELLED');
--> statement-breakpoint

CREATE TYPE appointment_status AS ENUM (
  'DRAFT', 'SCHEDULED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW'
);
--> statement-breakpoint

CREATE TABLE clinic (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text NOT NULL,
  timezone     text NOT NULL,              -- IANA, e.g. 'Asia/Kolkata'
  day_start    time NOT NULL DEFAULT '08:00',
  day_end      time NOT NULL DEFAULT '17:00',
  slot_minutes smallint NOT NULL DEFAULT 15,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT clinic_day_ordered CHECK (day_start < day_end),
  CONSTRAINT clinic_slot_minutes_positive CHECK (slot_minutes > 0)
);
--> statement-breakpoint

CREATE TABLE patient (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id     uuid NOT NULL REFERENCES clinic(id),
  mrn           text NOT NULL,
  full_name     text NOT NULL,
  date_of_birth date,
  phone         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (clinic_id, mrn)
);
--> statement-breakpoint

CREATE TABLE resource (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id     uuid NOT NULL REFERENCES clinic(id),
  type          resource_type NOT NULL,
  name          text NOT NULL,
  modalities    text[] NOT NULL DEFAULT '{}',
  display_order smallint NOT NULL DEFAULT 0,
  active        boolean NOT NULL DEFAULT true
);
--> statement-breakpoint

CREATE TABLE resource_working_hours (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id uuid NOT NULL REFERENCES resource(id) ON DELETE CASCADE,
  weekday     smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
  starts_at   time NOT NULL,
  ends_at     time NOT NULL,
  CHECK (starts_at < ends_at)
);
--> statement-breakpoint

-- Date-specific closure or extra availability. available=false blocks the window.
CREATE TABLE resource_exception (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id uuid NOT NULL REFERENCES resource(id) ON DELETE CASCADE,
  on_date     date NOT NULL,
  starts_at   time NOT NULL,
  ends_at     time NOT NULL,
  available   boolean NOT NULL DEFAULT false,
  reason      text,
  CHECK (starts_at < ends_at)
);
--> statement-breakpoint

CREATE TABLE service_type (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id         uuid NOT NULL REFERENCES clinic(id),
  code              text NOT NULL,
  name              text NOT NULL,
  resource_type     resource_type NOT NULL,
  required_modality text,
  UNIQUE (clinic_id, code)
);
--> statement-breakpoint

-- A saved, reusable chain. A read-only source to copy from; never referenced by
-- a booked appointment's scheduling logic. See spec 2.8 and the snapshot note on
-- appointment_step below.
CREATE TABLE appointment_template (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id  uuid NOT NULL REFERENCES clinic(id),
  code       text NOT NULL,
  name       text NOT NULL,
  is_preset  boolean NOT NULL DEFAULT true,
  active     boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (clinic_id, code)
);
--> statement-breakpoint

CREATE TABLE template_step (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id          uuid NOT NULL REFERENCES appointment_template(id) ON DELETE CASCADE,
  seq                  smallint NOT NULL,
  service_type_id      uuid NOT NULL REFERENCES service_type(id),
  duration_min         smallint NOT NULL CHECK (duration_min > 0),
  min_gap_min          smallint NOT NULL DEFAULT 0 CHECK (min_gap_min >= 0),
  max_gap_min          smallint NOT NULL DEFAULT 0 CHECK (max_gap_min >= 0),
  setup_min            smallint NOT NULL DEFAULT 0 CHECK (setup_min >= 0),
  teardown_min         smallint NOT NULL DEFAULT 0 CHECK (teardown_min >= 0),
  same_resource_as_seq smallint,
  UNIQUE (template_id, seq),
  CHECK (max_gap_min >= min_gap_min),
  CHECK (same_resource_as_seq IS NULL OR same_resource_as_seq < seq)
);
--> statement-breakpoint

CREATE TABLE appointment (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinic_id    uuid NOT NULL REFERENCES clinic(id),
  patient_id   uuid NOT NULL REFERENCES patient(id),
  -- Provenance only. NULL for a chain built from scratch. The authoritative
  -- chain lives in appointment_step; template edits never affect bookings.
  template_id  uuid REFERENCES appointment_template(id),
  template_name_at_booking text,
  on_date      date NOT NULL,
  status       appointment_status NOT NULL DEFAULT 'SCHEDULED',
  notes        text,
  created_by   uuid,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- The authoritative chain for THIS appointment, snapshotted at booking time.
-- Mirrors template_step, but owned by the appointment. This is what the
-- scheduling engine is built from and what a reschedule re-solves.
CREATE TABLE appointment_step (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id       uuid NOT NULL REFERENCES appointment(id) ON DELETE CASCADE,
  seq                  smallint NOT NULL,
  service_type_id      uuid NOT NULL REFERENCES service_type(id),
  duration_min         smallint NOT NULL CHECK (duration_min > 0),
  min_gap_min          smallint NOT NULL DEFAULT 0 CHECK (min_gap_min >= 0),
  max_gap_min          smallint NOT NULL DEFAULT 0 CHECK (max_gap_min >= 0),
  setup_min            smallint NOT NULL DEFAULT 0 CHECK (setup_min >= 0),
  teardown_min         smallint NOT NULL DEFAULT 0 CHECK (teardown_min >= 0),
  same_resource_as_seq smallint,
  UNIQUE (appointment_id, seq),
  CHECK (max_gap_min >= min_gap_min),
  CHECK (same_resource_as_seq IS NULL OR same_resource_as_seq < seq)
);
--> statement-breakpoint

CREATE TABLE appointment_segment (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id  uuid NOT NULL REFERENCES appointment(id) ON DELETE CASCADE,
  clinic_id       uuid NOT NULL REFERENCES clinic(id),
  patient_id      uuid NOT NULL REFERENCES patient(id),
  seq             smallint NOT NULL,
  kind            segment_kind NOT NULL,
  service_type_id uuid REFERENCES service_type(id),
  resource_id     uuid REFERENCES resource(id),
  during          tstzrange NOT NULL,   -- patient interval
  resource_during tstzrange,            -- resource interval, NULL for DELAY
  status          segment_status NOT NULL DEFAULT 'ACTIVE',

  -- A mandatory delay holds the patient and no clinical resource; a service
  -- step holds both. There is no third shape.
  CHECK (
    (kind = 'DELAY'   AND resource_id IS NULL     AND resource_during IS NULL) OR
    (kind = 'SERVICE' AND resource_id IS NOT NULL AND resource_during IS NOT NULL)
  ),
  -- The resource interval is the patient interval widened by setup and
  -- teardown, so it must contain it. Both are zero today (spec 2.4).
  CHECK (resource_during IS NULL OR resource_during @> during),

  -- No resource is ever in two places at once. Enforced by the database, not by
  -- application code, so it holds under any concurrency -- and also under a
  -- manual SQL edit or an application bug. An EXCLUDE constraint is an index
  -- that rejects a row whose (resource_id, resource_during) pair matches an
  -- existing row on = and overlaps on &&; btree_gist is what allows the uuid
  -- equality and the range overlap to share one GiST index.
  CONSTRAINT no_resource_double_book EXCLUDE USING gist (
    resource_id WITH =, resource_during WITH &&
  ) WHERE (status <> 'CANCELLED' AND resource_id IS NOT NULL),

  -- Same rule for the patient, who is modelled as a capacity-1 resource
  -- (ADR 0003). "Patient double-booked" and "scanner double-booked" are
  -- deliberately the same rule enforced by the same mechanism.
  CONSTRAINT no_patient_double_book EXCLUDE USING gist (
    patient_id WITH =, during WITH &&
  ) WHERE (status <> 'CANCELLED')
);
--> statement-breakpoint

CREATE INDEX appointment_segment_during_idx ON appointment_segment USING gist (during);
--> statement-breakpoint

-- Day queries filter on clinic and the segment's start instant. The lower bound
-- of the range is indexed directly rather than cast to a date, because
-- timestamptz -> date depends on the session TimeZone and so is only STABLE;
-- Postgres rejects a non-IMMUTABLE expression in an index. Callers scan a
-- half-open instant range for the day instead, which is index-friendlier anyway.
CREATE INDEX appointment_segment_clinic_start_idx
  ON appointment_segment (clinic_id, lower(during));
--> statement-breakpoint

CREATE INDEX appointment_clinic_date_status_idx ON appointment (clinic_id, on_date, status);
--> statement-breakpoint

-- Optimistic concurrency token, bumped on every write to a clinic-day.
CREATE TABLE schedule_version (
  clinic_id uuid NOT NULL REFERENCES clinic(id),
  on_date   date NOT NULL,
  version   bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (clinic_id, on_date)
);
--> statement-breakpoint

CREATE TABLE audit_log (
  id        bigserial PRIMARY KEY,
  clinic_id uuid NOT NULL,
  actor_id  uuid,
  action    text NOT NULL,
  entity    text NOT NULL,
  entity_id uuid,
  before    jsonb,
  after     jsonb,
  at        timestamptz NOT NULL DEFAULT now()
);
