export {
  APPOINTMENT_STATUSES,
  appointmentStatusSchema,
  ENUM_VALUES,
  RESOURCE_TYPES,
  resourceTypeSchema,
  SEGMENT_KINDS,
  SEGMENT_STATUSES,
  segmentKindSchema,
  segmentStatusSchema,
  type AppointmentStatus,
  type ResourceType,
  type SegmentKind,
  type SegmentStatus,
} from './enums.js';
