export {
  APPOINTMENT_STATUSES,
  ENUM_VALUES,
  RESOURCE_TYPES,
  SEGMENT_KINDS,
  SEGMENT_STATUSES,
  USER_ROLES,
  appointmentStatusSchema,
  resourceTypeSchema,
  segmentKindSchema,
  segmentStatusSchema,
  userRoleSchema,
  type AppointmentStatus,
  type ResourceType,
  type SegmentKind,
  type SegmentStatus,
  type UserRole,
} from './enums.js';

export {
  chainStepSchema,
  parseAppointmentChain,
  type ChainResource,
  type ChainServiceType,
  type ChainStep,
  type ChainValidationContext,
} from './chain.js';

export {
  APPOINTMENT_STATUS_TRANSITIONS,
  allowedTransitions,
  canTransition,
} from './status-transitions.js';

export {
  appointmentDetailSchema,
  appointmentTemplateDetailSchema,
  appointmentTemplateSummarySchema,
  auditEntrySchema,
  bookAppointmentBodySchema,
  bookAppointmentResponseSchema,
  bookedSegmentSchema,
  cancelAppointmentBodySchema,
  candidateSchema,
  chosenCandidateSchema,
  clinicDateSchema,
  createAppointmentTemplateBodySchema,
  createPatientBodySchema,
  currentUserSchema,
  getScheduleQuerySchema,
  getScheduleResponseSchema,
  healthResponseSchema,
  instantSchema,
  listAppointmentsQuerySchema,
  listAppointmentsResponseSchema,
  listAuditQuerySchema,
  listAuditResponseSchema,
  listPatientsQuerySchema,
  loginBodySchema,
  patientSchema,
  placementSchema,
  problemDetailsSchema,
  readyResponseSchema,
  rescheduleAppointmentBodySchema,
  resourceDtoSchema,
  scheduleAppointmentSchema,
  scheduleLaneSchema,
  scheduleResourceSchema,
  scheduleSegmentSchema,
  serviceTypeDtoSchema,
  sessionResponseSchema,
  suggestAppointmentsBodySchema,
  suggestAppointmentsResponseSchema,
  type AppointmentDetail,
  type AuditEntry,
  type AppointmentTemplateDetail,
  type BookAppointmentBody,
  type BookAppointmentResponse,
  type CancelAppointmentBody,
  type CandidateDto,
  type ClinicDate,
  type CreateAppointmentTemplateBody,
  type CreatePatientBody,
  type CurrentUser,
  type GetScheduleQuery,
  type GetScheduleResponse,
  type ScheduleAppointment,
  type ScheduleSegment,
  type Instant,
  type ListAppointmentsQuery,
  type ListAppointmentsResponse,
  type ListAuditQuery,
  type ListAuditResponse,
  type ListPatientsQuery,
  type LoginBody,
  type PatientDto,
  type PlacementDto,
  type ProblemDetails,
  type RescheduleAppointmentBody,
  type ResourceDto,
  type ServiceTypeDto,
  type SessionResponse,
  type SuggestAppointmentsBody,
  type SuggestAppointmentsResponse,
} from './http.js';
